const API_URL = process.env.API_BASE_URL;
const SESSION_SECRET = process.env.SESSION_SECRET;
const API_TOKEN = process.env.NEXT_PUBLIC_API_TOKEN;
const API_TOKEN_EXPIRES_AT = process.env.NEXT_PUBLIC_API_TOKEN_EXPIRES_AT;
const API_TOKEN_REFRESH_INTERVAL = process.env.NEXT_PUBLIC_API_TOKEN_REFRESH_INTERVAL;

export const env = {
  API_URL,
  SESSION_SECRET,
  API_TOKEN,
  API_TOKEN_EXPIRES_AT,
  API_TOKEN_REFRESH_INTERVAL,
};